[package]
name = "security"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
overflow-checks = true
opt-level = 3

[dependencies]
mimalloc = { version = "*", features = ["secure"] }
untrusted = "*"